### ISSUE TITLE
Move Slack ping to a background job with perform_later

### ISSUE THREAD

**Issue by scott** [scott/helpy_slack#1]
Helpy ships with the `sucker_punch` in-memory queue and uses standard `ActiveJob` constructs.  This gem should use a background job to handle pinging the webhook.

To complete this enhancement:
- Add a background job for pinging the webhook
- Modify the after_create hook to create the job instead of pinging directly to Slack

**Comment by shaktik1989** [comment]
I have created a pull request regarding this, Please have a look and let me know your thoughts.
